githubConfigUrl: "https://github.com/Kofoten/oevent-course-helper"
githubConfigSecret: "arc-github-app-secret"
runnerScaleSetName: "oevent-course-helper-arc-runner"

template:
  spec:
    containers:
      - name: runner
        image: local/dotnet8-runner:v2
        imagePullPolicy: IfNotPresent
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
